language: node_js
node_js:
  - "10.6.0"
install:
  - yarn install
script:
  - yarn run lint
  - yarn run coverage
  - yarn run test:ci
after_script:
  - yarn global add coveralls
  - coveralls < ./coverage/lcov.info
